//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationFinal.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerInstrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OwnerInstrument()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int OwnerInstrumentID { get; set; }
        public string InstrumentName { get; set; }
        public string OwnerID { get; set; }
        public string InstrumentPhoto { get; set; }
        public string SpecialNotes { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int InstrumentTypeID { get; set; }
    
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual UserDetail UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
